### ISSUE TITLE
[Bug] Duplicated newly imported account

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#104]
**Describe the bug**
The app shows duplicated newly imported account

**To Reproduce**
1. Create new Wallet 
2. Create new Account in popup => Account 2
3. Import Account by copying private key from CasperSigner, name it "Main"
4. It show duplicated "Main" accounts which are same public key

**Expected behavior**
Should show only one imported account

**Screenshots**
![IMG_6618](https://user-images.githubusercontent.com/4486806/190349885-6bbffaf0-0e5a-4ea2-b2dd-e39b718b34e3.png)

**Smartphone (please complete the following information):**
 - Device: iphoneX
 - Version: 1.1.0 (8)

**Comment by kienthemartec** [comment]
https://github.com/CasperDash/casperdash-mobile-wallet/pull/94/commits/1285df7775c5cfbd63ff8faefac6c3c5c4426934
fixed

**Comment by gaupoit** [comment]
I will double check and close it in the next build.

**Comment by gaupoit** [comment]
It has been resolved in 1.1.0 (10)
