### ISSUE TITLE
The app should disable the undelegate button when the deploy is pending.

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#113]
**Describe the bug**
The app should disable the undelegate button when the deploy is pending.

**To Reproduce**
1. Import wallet which having the staking amount
2. Go to Staking screen
3. Click on Undelegate in any records
4. Still can click on the Undelegate in the record having pending deploy

**Expected behavior**
Should disable the `Undelegate` button and show Pending status following the design

![Screen Shot 2022-09-20 at 11 28 55](https://user-images.githubusercontent.com/4486806/191167666-91ddff38-85e5-4110-98ec-b9c7aac9d9b8.png)

**Screenshots**
![Screenshot_20220920-112911_CasperDash](https://user-images.githubusercontent.com/4486806/191167868-f54780bc-3a54-472d-ad38-cc88b003482b.jpg)

**Smartphone (please complete the following information):**
 - OS: iOS
 - Version: 1.1.0 (10)

**Comment by gaupoit** [comment]
I suggest we should set this task high priority and release it on 1.1.0. The staking screen will be used a lot by users when we are running the staking tournament campaign. We need to bring the best user experiences on this screen.

**Comment by djhahe** [comment]
![image](https://user-images.githubusercontent.com/6711653/195759692-08a0d2ad-c93a-4d9d-a81f-319fddcd912d.png)

**Comment by djhahe** [comment]
fixed 1.1.0 - 23

**Comment by gaupoit** [comment]
![IMG_3B875049B20A-1](https://user-images.githubusercontent.com/4486806/196323981-7a3d7c9f-c9ae-4bb3-ad5b-d1dfe7a8aff0.jpeg)

LGTM
