### ISSUE TITLE
[Improvement] Should use the same the decimal places format for currencies display 

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#115]
**Is your feature request related to a problem? Please describe.**
We should use the same the decimal places format for currencies display  

**Describe the solution you'd like**
![create-account](https://user-images.githubusercontent.com/4486806/191217310-a83ef091-5f33-4d0c-a08d-a0634c6d8013.png)

![home](https://user-images.githubusercontent.com/4486806/191217409-26bd6227-f4e6-49f3-91e6-f1390a69c75c.png)

![staking](https://user-images.githubusercontent.com/4486806/191217621-835a8cc2-595e-4cc7-bb1c-361f65736189.png)

![market](https://user-images.githubusercontent.com/4486806/191217746-0f4179b8-450f-480c-9da0-40049f1d9ab3.png)

![undelegate](https://user-images.githubusercontent.com/4486806/191218137-f0236310-025b-4ac3-907d-395a0a6f173f.png)

**Describe alternatives you've considered**
Ref PR: https://github.com/CasperDash/casperdash-client/pull/132/files (Extensions is using 4 decimal places)

**Additional context**

**Comment by djhahe** [comment]
We should handle the decimal place case by case.
e.g if price of CSPR is too low, we need to add more decimal place to the price vice versa with balance
