### ISSUE TITLE
[Send Screen] Display -0.1 in transfer amount

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#119]
**Describe the bug**
It displays -0.1 in the transfer amount when the wallet balance is 0.

**To Reproduce**
1. Create new account
2. Go to Send Screen
3. Click on Max button on the Transfer Amount input's field
4. It show -0.1 in transfer amount field

**Expected behavior**
It should show 0
![IMG_1976](https://user-images.githubusercontent.com/4486806/192189736-7bac2a6d-2b53-45da-9a18-ac083cfac566.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - Version: 1.1.0 (20)

**Comment by djhahe** [comment]
fixed

**Comment by gaupoit** [comment]
LGTM
