### ISSUE TITLE
[Ledger] Improve error handling when the ledger device is unavailable - the app tends to hang

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#140]
**Describe the bug**
When the ledger device is unavailable , the app tends to hang w/o showing any error messages. 

**To Reproduce**
TBU

**Expected behavior**
The app show should the friendly error message.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - Version: 1.1.4

**Additional context**
N/A

**Comment by djhahe** [comment]
Close this for now, pls reopen if the issue's still reducible
