### ISSUE TITLE
Fallback Error Screen and Crash Reporting

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-mobile-wallet#179]
**Is your feature request related to a problem? Please describe.**
Adding a fallback error screen and integrating Crashlytics into the application to prevent crashes and improve error reporting.

**Describe the solution you'd like**
- The fallback error screen will be displayed to the user in case of any unexpected errors or exceptions that would cause the application to crash.
- FireBase/Crashlytics will be integrated into the application to capture crash reports, exceptions, and error logs.

**Comment by gaupoit** [comment]
hi @djhahe , have we released this task?
