### ISSUE TITLE
Taking too long 

### ISSUE THREAD

**Issue by MarcelKrawiec** [CasperDash/casperdash-mobile-wallet#231]
I'm trying to redelegate from one validator to another. So far it is taking over 36h. I haven't got access to my founds

**Comment by hoailinh1210** [comment]
Hi @MarcelKrawiec,
Our team can help you quickly if you send your message to the Telegram group.
Telegram: [https://t.me/CasperDash_Official](https://t.me/CasperDash_Official)

**Comment by djhahe** [comment]
This's fixed in v2.3.1

**Comment by MarcelKrawiec** [comment]
What is fixed ?
I can't see my Cspr tokens

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
