### ISSUE TITLE
[UX Issue] Should align left for the back button

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#241]
**Describe the bug**
![Screenshot 2023-10-05 at 14 49 13](https://github.com/CasperDash/casperdash-mobile-wallet/assets/4486806/f9a54270-0569-4bcb-bbca-5700eeedbfe7)

Following the home page. 
![Screenshot 2023-10-05 at 14 50 49](https://github.com/CasperDash/casperdash-mobile-wallet/assets/4486806/b12c05a0-d9ac-4e85-bbe9-55489f4f9ec0)

**Should apply align left for the buttons in every pages.**

**Comment by djhahe** [comment]
This one related to web version
