### ISSUE TITLE
[Bug] Should redirect to custom token after transfer

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#46]
After transfer custom token successfully, the app should redirect me to custom token histories. Currently, it redirect me to CSPR history screen.

**Comment by ThanhNguyen140797** [comment]
Hi @gaupoit Click the custom token and click Send in Histories screen, right?

<img width="436" alt="Screen Shot 2022-03-06 at 12 27 46" src="https://user-images.githubusercontent.com/34257375/156910492-3118c24a-07fc-4b3c-8eac-b362d2a5f293.png">

**Comment by ThanhNguyen140797** [comment]
#48
