### ISSUE TITLE
[Bug] Send Custom Token Issues

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#47]
As the users I can send custom token (but the transaction is failed) when do following steps:

1. Choose send button in Home
2. Choose custom token Asset in Send form (Eg: Ghost)
3. Click send
4. The deploy can review and the app records the transactions.
![Image from iOS](https://user-images.githubusercontent.com/4486806/156913256-58fe4015-d80c-404a-a52f-1d7ddeedd3f6.png)
5. Later, the transaction's status is Failed.

![IMG_2970E4BBF05E-1](https://user-images.githubusercontent.com/4486806/156913294-dba1fe8b-0688-4ea0-9267-b8f3161c85a1.jpeg)

On the other hand, I cannot send custom token when do following steps 

1. Choose custom token in Home
2. Click send button
3. When click send, it informs the error message

![IMG_9CBF7F92B5F8-1](https://user-images.githubusercontent.com/4486806/156913376-d603c958-f183-4c32-b1e0-13268e6a44c9.jpeg)

**Comment by gaupoit** [comment]
I suggest the app should handle one way that inform the "Unsupported Deploy" whatever the cases to send custom token.

**Comment by ThanhNguyen140797** [comment]
#48
