### ISSUE TITLE
[Send CSPR] Add QR Code icon and Screen

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#67]
- Add QR Code icon in "Send CSPR" screen

![Screen Shot 2022-04-05 at 20 55 39](https://user-images.githubusercontent.com/4486806/161770210-4cc6070e-6d9b-4fc3-8f53-beaefb14d0f2.png)

![Screen Shot 2022-04-05 at 20 57 40](https://user-images.githubusercontent.com/4486806/161770507-f8c88587-298d-4f16-945e-83fa3ca684ec.png)

^ Notes: please remove the "Cancel" button.

**Comment by ThanhNguyen140797** [comment]
#74
