### ISSUE TITLE
[Recovery phase] update to 24 -> 12 words

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-mobile-wallet#89]

**Comment by djhahe** [comment]
![image](https://user-images.githubusercontent.com/6711653/185952753-32b318f5-1dad-432e-a008-cbbe5e1e6b04.png)

**Comment by gaupoit** [comment]
https://github.com/CasperDash/casperdash-mobile-wallet/pull/94/files#diff-e695e4ee4f3340e7099d843a16c83837199c0d4465fcab90a6b81af4241803f8R21 it has been done before though. hi @hoailinh1210 please help to fix the above UI issue then.
