### ISSUE TITLE
[Account management] Add dropdown to chose encryption type

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-mobile-wallet#93]

**Comment by gaupoit** [comment]
Related UI
![Screen Shot 2022-08-25 at 08 08 29](https://user-images.githubusercontent.com/4486806/186551151-aaa8bd26-4d4a-4bb7-a410-3e220862d7a3.png)

Please re-use this drop down list with label "Encryption Type".
![Screen Shot 2022-08-25 at 08 09 35](https://user-images.githubusercontent.com/4486806/186551270-299fa57f-5f6a-4e79-ab17-03b4dd8a234b.png)
